import { BrowserView } from "electrobun/bun";
import { MAIN_VIEW_RPC_MAX_REQUEST_TIME_MS } from "../../shared/constants";
import type { MainViewRPC } from "../../shared/rpc/types";
import {
  closeWindow,
  completeMicrosoftProfileLogin,
  createLauncherInstance,
  createLauncherProfile,
  createLaunchPlan,
  deleteLauncherInstance,
  downloadArtifacts,
  downloadCurseForgeFile,
  getCurseForgeStatus,
  getDatabaseStatus,
  getEnvironment,
  getInstanceContent,
  getLauncherStatus,
  getMinecraftVersionDetails,
  getSettingsStatus,
  getSystemMemory,
  getWindowState,
  greet,
  installDownloadedCurseForgeFile,
  launchInstance,
  listLauncherInstances,
  listLauncherProfiles,
  listLoaderVersions,
  listMinecraftVersions,
  logToBun,
  minimizeWindow,
  openExternal,
  pollMicrosoftProfileSignIn,
  refreshMinecraftVersionManifest,
  searchCurseForgeProjects,
  setInstanceModEnabled,
  startMicrosoftProfileLogin,
  toggleMaximizeWindow,
  updateLauncherInstance,
  updateSetting,
} from "./handlers";

export const mainViewRPC = BrowserView.defineRPC<MainViewRPC>({
  handlers: {
    messages: {
      logToBun,
    },
    requests: {
      closeWindow,
      completeMicrosoftProfileLogin,
      createLaunchPlan,
      createLauncherInstance,
      createLauncherProfile,
      deleteLauncherInstance,
      downloadArtifacts,
      downloadCurseForgeFile,
      getCurseForgeStatus,
      getDatabaseStatus,
      getEnvironment,
      getInstanceContent,
      getLauncherStatus,
      getMinecraftVersionDetails,
      getSettingsStatus,
      getSystemMemory,
      getWindowState,
      greet,
      installDownloadedCurseForgeFile,
      launchInstance,
      listLauncherInstances,
      listLauncherProfiles,
      listLoaderVersions,
      listMinecraftVersions,
      minimizeWindow,
      openExternal,
      pollMicrosoftProfileSignIn,
      refreshMinecraftVersionManifest,
      searchCurseForgeProjects,
      setInstanceModEnabled,
      startMicrosoftProfileLogin,
      toggleMaximizeWindow,
      updateLauncherInstance,
      updateSetting,
    },
  },
  maxRequestTime: MAIN_VIEW_RPC_MAX_REQUEST_TIME_MS,
});
